### ISSUE TITLE
Upload PDF Files

### ISSUE THREAD

**Issue by Jhonattan38G** [RQDA/RQDA#15]
Thanks, @JanMarvin, so far it has worked for me without any problem, I am from Colombia and I wanted you to help me with a problem.
I try to upload PDF files because I also want to add this type of document in my analysis and my work, but I don't know how, I was looking and it requires the dependency of rjpod.
This is the process that I carry out:

##################
> install.packages("rJava")
Installing package into ‘C:/Users/JhonattanHOME/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
probando la URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.0/rJava_0.9-13.zip'
Content type 'application/zip' length 1115175 bytes (1.1 MB)
downloaded 1.1 MB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\JhonattanHOME\AppData\Local\Temp\Rtmp4sSK8a\downloaded_packages
> library(rJava)
> RQDA()
Extracting highlight ...
Error in loadNamespace(name) : there is no package called ‘rjpod’

> install.packages("rjpod")
Installing package into ‘C:/Users/JhonattanHOME/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning message:
package ‘rjpod’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
>
#############
   @###
I need to upload PDF files, but I don't know how to do it, I've already seen other ways but I can't find the key point either.

**Comment by JanMarvin** [comment]
Hi @Jhonattan38G, I am not entirely sure what you are trying to do. The best approach would be to convert the PDF files to txt files. Either via some r-package of which I'm currently unaware of, but maybe some other pdf to txt program.

**Comment by Jhonattan38G** [comment]
Sorry, my English is not very good haha.
Thanks @BroVic , I will implement that package to review pdf documents in RQDA.
I've been looking at other packages for this feature.
Install the following packages:
install.packages (rJava).
install.packages ("rjpod", INSTALL_opts = "- no-multiarch", repos = "http://R-Forge.R-project.org").
To open a PDF document, you have to select the text, open a pdf reader (adobe acrobat Pro or PDFXChange Viewer) and in the document preferences option select the option "copy the selected text in Highlight, Strike Out and underline the pop-up comment - ups "(screenshot added), after opening the document and underlining the desired text and finally executing the library (RQDA), in the files section right click and in the option" import PDF highlights via rjpod (selector) "choose the Modified PDF document, you can see only the underlined text and finally it can be encoded with RQDA without problems. 
![imagen](https://user-images.githubusercontent.com/82534155/114928403-2e598100-9df8-11eb-914e-1db83651b3c0.png)

**Comment by JanMarvin** [comment]
Sorry for asking again, is there an issue with rqda? Otherwise I'd close this issue.

As stated, the best approach would be to convert any text from a PDF file independent of rqda. It would be possible to embed other languages into rqda when importing certain file formats, but there are certain tradeoffs to that. For example, since PDFs do not have specific text body areas, and there is a high probability that page numbers and headlines would be imported for every page. Therefore I'd suggest to do the file to text conversion ahead of the import. This allows for better fine running when using certain tools and full featured text editors.

**Comment by Jhonattan38G** [comment]
No, I have no problems, thank you very much for the help, it's a good job @JanMarvin 

Greetings
