### ISSUE TITLE
The RQDA graffic interface  doesn't work all functions 

### ISSUE THREAD

**Issue by samirnemechaves** [RQDA/RQDA#17]
I have been working with RQDA, I have installed it since your GitHub... I could say that works the principal things, but others don't work. For example,  I can't have access to secondary menus in the right-click mouse, that situation doesn't let me among other Plot the categories, a function that is important to my work 

I appreciate some help with that problem, thank you

**Comment by JanMarvin** [comment]
Hi again, I've tested it and it works for me. I can watch Networks with igraph in tk and with d3SimpleNetwork in the webbrowser.
