### ISSUE TITLE
Color settings functionality not working

### ISSUE THREAD

**Issue by ejosully** [RQDA/RQDA#18]
Version:0.3-2

Steps to replicate:
- Go to Settings
- Change either of the "Color for Coding" or "Color for Case" settings
- Click OK
- Open a file

Expected functionality:
- Codes / case information is highlighted in the color selected in the settings menu

Observed functionality:
- Codes are highlighted in the default blue color, case information is highlighted in the default gold color

**Comment by JanMarvin** [comment]
Thanks, fixed!

**Comment by ejosully** [comment]
Thank you so much, my eyes are much happier :D
